# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-17 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLifeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dClass', models.CharField(max_length=50, verbose_name='类')),
                ('dSmallImage', models.ImageField(default='', upload_to='dailylife/small/', verbose_name='小图片')),
                ('dLargerImage', models.ImageField(default='', upload_to='dailylife/large/', verbose_name='大图片')),
                ('dContent', models.CharField(blank=True, max_length=1000, verbose_name='内容')),
            ],
            options={
                'verbose_name': '日常生活',
                'verbose_name_plural': '日常生活',
                'ordering': ['id'],
            },
        ),
    ]
