# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-18 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentMessageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='联系人姓名')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='邮箱地址')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='电话')),
                ('theme', models.CharField(blank=True, max_length=50, null=True, verbose_name='主题')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('message', models.TextField(verbose_name='信息')),
            ],
            options={
                'verbose_name': '联系人信息',
                'verbose_name_plural': '联系人信息',
                'ordering': ['id'],
            },
        ),
    ]
