# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-18 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20190518_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmessagemodel',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='信息'),
        ),
    ]
