# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-16 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviemodel',
            name='mAuthor',
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='mName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='电影名'),
        ),
    ]
