# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-16 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0002_auto_20190516_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='bDelay',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='偏移量'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='bComment',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='书籍评价'),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='mComment',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='电影评价'),
        ),
    ]
