# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-17 00:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0004_auto_20190517_0039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firstbookmodel',
            options={'ordering': ['id'], 'verbose_name': '书籍推荐1', 'verbose_name_plural': '书籍推荐1'},
        ),
        migrations.AlterModelOptions(
            name='secondbookmodel',
            options={'ordering': ['id'], 'verbose_name': '书籍推荐2', 'verbose_name_plural': '书籍推荐2'},
        ),
    ]
