# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-22 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='网站名称')),
                ('url', models.URLField(max_length=50, verbose_name='网站链接')),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['index', 'id'], 'verbose_name': '内容分类', 'verbose_name_plural': '内容分类'},
        ),
    ]
