# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-22 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190422_1842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='website',
            options={'verbose_name': '门户网站', 'verbose_name_plural': '门户网站'},
        ),
    ]
