# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-22 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190422_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeWelcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content1', models.TextField(max_length=200, verbose_name='内容1')),
                ('content2', models.TextField(max_length=200, verbose_name='内容2')),
                ('image1', models.ImageField(upload_to='home/%Y/%m', verbose_name='图片1路径')),
                ('image2', models.ImageField(upload_to='home/&Y/%m', verbose_name='图片2路径')),
            ],
        ),
    ]
