# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-22 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homewelcome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homewelcome',
            options={'ordering': ['id'], 'verbose_name': '主页欢迎', 'verbose_name_plural': '主页欢迎'},
        ),
        migrations.AlterModelOptions(
            name='website',
            options={'ordering': ['id'], 'verbose_name': '门户网站', 'verbose_name_plural': '门户网站'},
        ),
        migrations.AddField(
            model_name='website',
            name='index',
            field=models.IntegerField(default=999, verbose_name='网站排序'),
        ),
    ]
