# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-22 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190422_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homewelcome',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='homewelcome',
            name='image2',
        ),
        migrations.AlterField(
            model_name='homewelcome',
            name='content1',
            field=models.CharField(max_length=200, verbose_name='内容1'),
        ),
        migrations.AlterField(
            model_name='homewelcome',
            name='content2',
            field=models.CharField(max_length=200, verbose_name='内容2'),
        ),
    ]
