# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-23 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190422_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='homewelcome',
            name='pic1_path',
            field=models.ImageField(default='pic_folder/None/no_image1.pig', upload_to='pic_folder', verbose_name='图片1路径'),
        ),
        migrations.AddField(
            model_name='homewelcome',
            name='pic2_path',
            field=models.ImageField(default='pic_folder/None/no_image2.pig', upload_to='pic_folder/', verbose_name='图片2路径'),
        ),
    ]
