# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-28 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_djangostudy_pythonstudy_spiderstudy_webstudy'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socialMode', models.CharField(blank=True, max_length=50, verbose_name='社交方式')),
                ('socialName', models.CharField(blank=True, max_length=50, verbose_name='社交内容')),
            ],
            options={
                'verbose_name': '社交',
                'verbose_name_plural': '社交',
                'ordering': ['id'],
            },
        ),
    ]
