# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-30 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20190430_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmode',
            name='socialClass',
            field=models.CharField(blank=True, max_length=50, verbose_name='社交样式'),
        ),
        migrations.AlterField(
            model_name='spiderstudy',
            name='source',
            field=models.CharField(blank=True, max_length=50, verbose_name='Spider学习'),
        ),
        migrations.AlterField(
            model_name='spiderstudy',
            name='sourceUrl',
            field=models.URLField(blank=True, max_length=50, verbose_name='Spider学习连接'),
        ),
    ]
