# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-14 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20190430_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentWorkModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workName', models.CharField(blank=True, max_length=50, verbose_name='工作名')),
                ('workImage', models.ImageField(default='/static/images/default.png', upload_to='recentWork', verbose_name='图片路径')),
                ('workContent', models.CharField(blank=True, max_length=50, verbose_name='工作内容')),
                ('index', models.IntegerField(default=999, verbose_name='排序')),
            ],
            options={
                'verbose_name': '最近工作',
                'verbose_name_plural': '最近工作',
                'ordering': ['index', 'id'],
            },
        ),
    ]
