# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-14 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_recentworkmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentworkmodel',
            name='workImage',
            field=models.ImageField(upload_to='recentWork', verbose_name='图片路径'),
        ),
    ]
