# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-14 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20190514_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recentworkmodel',
            name='workImage',
        ),
        migrations.AddField(
            model_name='recentworkmodel',
            name='largerImage',
            field=models.ImageField(default='', upload_to='recentWork/larger/', verbose_name='大图片路径'),
        ),
        migrations.AddField(
            model_name='recentworkmodel',
            name='smallImage',
            field=models.ImageField(default='', upload_to='recentWork/small/', verbose_name='小图片路径'),
        ),
    ]
