# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-16 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20190516_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='humorousjokemodel',
            name='pId',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='humorousjokemodel',
            name='pContent',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='内容'),
        ),
    ]
