# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-17 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20190516_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='app',
            field=models.CharField(default='', max_length=30, verbose_name='app'),
        ),
    ]
