# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-18 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_remove_category_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.CharField(default='', max_length=30, verbose_name='url'),
        ),
    ]
