# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-27 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_category_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funnyparagraphmodel',
            name='pClass',
            field=models.CharField(default='', max_length=50, verbose_name='类'),
        ),
        migrations.AlterField(
            model_name='funnyparagraphmodel',
            name='pContent',
            field=models.CharField(default='', max_length=5000, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='funnyparagraphmodel',
            name='pId',
            field=models.CharField(max_length=50, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='humorousjokemodel',
            name='pContent',
            field=models.CharField(default='', max_length=5000, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='humorousjokemodel',
            name='pId',
            field=models.CharField(default='', max_length=50, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='recentworkmodel',
            name='workContent',
            field=models.CharField(max_length=50, verbose_name='工作内容'),
        ),
        migrations.AlterField(
            model_name='recentworkmodel',
            name='workName',
            field=models.CharField(max_length=50, verbose_name='工作名'),
        ),
        migrations.AlterField(
            model_name='socialmode',
            name='socialClass',
            field=models.CharField(max_length=50, verbose_name='社交样式'),
        ),
        migrations.AlterField(
            model_name='socialmode',
            name='socialMode',
            field=models.CharField(max_length=50, verbose_name='社交方式'),
        ),
        migrations.AlterField(
            model_name='socialmode',
            name='socialName',
            field=models.CharField(max_length=50, verbose_name='社交内容'),
        ),
    ]
