# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-27 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20190527_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funnyparagraphmodel',
            name='pId',
            field=models.CharField(default='', max_length=50, verbose_name='id'),
        ),
    ]
