# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-19 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190519_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='date_publish',
            field=models.DateTimeField(verbose_name='发布时间'),
        ),
    ]
