# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-19 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190519_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='date_publish',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布时间'),
        ),
    ]
