# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-20 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190519_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='pid',
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='邮箱地址'),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='电话'),
        ),
    ]
