# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-20 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_commentmodel_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='article',
        ),
        migrations.RemoveField(
            model_name='commentmodel',
            name='phone',
        ),
    ]
